/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Primitives
        "lime-uma": {
          50: "var(--color-lime-uma-50)",
          100: "var(--color-lime-uma-100)",
          200: "var(--color-lime-uma-200)",
          300: "var(--color-lime-uma-300)",
          400: "var(--color-lime-uma-400)",
          500: "var(--color-lime-uma-500)",
          600: "var(--color-lime-uma-600)",
          700: "var(--color-lime-uma-700)",
          800: "var(--color-lime-uma-800)",
          900: "var(--color-lime-uma-900)",
          950: "var(--color-lime-uma-950)",
        },
        violet: {
          50: "var(--color-violet-50)",
          100: "var(--color-violet-100)",
          200: "var(--color-violet-200)",
          300: "var(--color-violet-300)",
          400: "var(--color-violet-400)",
          500: "var(--color-violet-500)",
          600: "var(--color-violet-600)",
          700: "var(--color-violet-700)",
          800: "var(--color-violet-800)",
          900: "var(--color-violet-900)",
          950: "var(--color-violet-950)",
        },
        sky: {
          50: "var(--color-sky-50)",
          100: "var(--color-sky-100)",
          200: "var(--color-sky-200)",
          300: "var(--color-sky-300)",
          400: "var(--color-sky-400)",
          500: "var(--color-sky-500)",
          600: "var(--color-sky-600)",
          700: "var(--color-sky-700)",
          800: "var(--color-sky-800)",
          900: "var(--color-sky-900)",
          950: "var(--color-sky-950)",
        },
        berry: {
          50: "var(--color-berry-50)",
          100: "var(--color-berry-100)",
          200: "var(--color-berry-200)",
          300: "var(--color-berry-300)",
          400: "var(--color-berry-400)",
          500: "var(--color-berry-500)",
          600: "var(--color-berry-600)",
          700: "var(--color-berry-700)",
          800: "var(--color-berry-800)",
          900: "var(--color-berry-900)",
          950: "var(--color-berry-950)",
        },
        amber: {
          50: "var(--color-amber-50)",
          100: "var(--color-amber-100)",
          200: "var(--color-amber-200)",
          300: "var(--color-amber-300)",
          400: "var(--color-amber-400)",
          500: "var(--color-amber-500)",
          600: "var(--color-amber-600)",
          700: "var(--color-amber-700)",
          800: "var(--color-amber-800)",
          900: "var(--color-amber-900)",
          950: "var(--color-amber-950)",
        },
        cucumber: {
          50: "var(--color-cucumber-50)",
          100: "var(--color-cucumber-100)",
          200: "var(--color-cucumber-200)",
          300: "var(--color-cucumber-300)",
          400: "var(--color-cucumber-400)",
          500: "var(--color-cucumber-500)",
          600: "var(--color-cucumber-600)",
          700: "var(--color-cucumber-700)",
          800: "var(--color-cucumber-800)",
          900: "var(--color-cucumber-900)",
          950: "var(--color-cucumber-950)",
        },
        gray: {
          50: "var(--color-gray-50)",
          100: "var(--color-gray-100)",
          200: "var(--color-gray-200)",
          300: "var(--color-gray-300)",
          400: "var(--color-gray-400)",
          500: "var(--color-gray-500)",
          600: "var(--color-gray-600)",
          700: "var(--color-gray-700)",
          800: "var(--color-gray-800)",
          900: "var(--color-gray-900)",
          950: "var(--color-gray-950)",
        },
        "warm-gray": {
          50: "var(--color-warm-gray-50)",
          100: "var(--color-warm-gray-100)",
          200: "var(--color-warm-gray-200)",
          300: "var(--color-warm-gray-300)",
          400: "var(--color-warm-gray-400)",
          500: "var(--color-warm-gray-500)",
          600: "var(--color-warm-gray-600)",
          700: "var(--color-warm-gray-700)",
          800: "var(--color-warm-gray-800)",
          900: "var(--color-warm-gray-900)",
          950: "var(--color-warm-gray-950)",
        },
        "slate-purple": {
          50: "var(--color-slate-purple-50)",
          100: "var(--color-slate-purple-100)",
          200: "var(--color-slate-purple-200)",
          300: "var(--color-slate-purple-300)",
          400: "var(--color-slate-purple-400)",
          500: "var(--color-slate-purple-500)",
          600: "var(--color-slate-purple-600)",
          700: "var(--color-slate-purple-700)",
          800: "var(--color-slate-purple-800)",
          900: "var(--color-slate-purple-900)",
          950: "var(--color-slate-purple-950)",
        },
        // Semantic Surfaces
        surface: {
          base: {
            DEFAULT: "var(--surface-base-default)",
            hover: "var(--surface-base-default-hover)",
            secondary: "var(--surface-base-secondary)",
            "secondary-hover": "var(--surface-base-secondary-hover)",
          },
          neutral: {
            DEFAULT: "var(--surface-neutral-default)",
            hover: "var(--surface-neutral-default-hover)",
            secondary: "var(--surface-neutral-secondary)",
            "secondary-hover": "var(--surface-neutral-secondary-hover)",
            tertiary: "var(--surface-neutral-tertiary)",
            "tertiary-hover": "var(--surface-neutral-tertiary-hover)",
          },
          brand: {
            DEFAULT: "var(--surface-brand-default)",
            hover: "var(--surface-brand-default-hover)",
            subtle: "var(--surface-brand-subtle)",
            secondary: "var(--surface-brand-secondary)",
            "secondary-hover": "var(--surface-brand-secondary-hover)",
          },
          "accent-1": {
            DEFAULT: "var(--surface-accent-1-default)",
            hover: "var(--surface-accent-1-default-hover)",
            secondary: "var(--surface-accent-1-secondary)",
            "secondary-hover": "var(--surface-accent-1-secondary-hover)",
            tertiary: "var(--surface-accent-1-tertiary)",
            "tertiary-hover": "var(--surface-accent-1-tertiary-hover)",
          },
          "accent-2": {
            DEFAULT: "var(--surface-accent-2-default)",
            hover: "var(--surface-accent-2-default-hover)",
            secondary: "var(--surface-accent-2-secondary)",
            "secondary-hover": "var(--surface-accent-2-secondary-hover)",
          },
          danger: {
            DEFAULT: "var(--surface-danger-default)",
            hover: "var(--surface-danger-default-hover)",
            secondary: "var(--surface-danger-secondary)",
            "secondary-hover": "var(--surface-danger-secondary-hover)",
          },
          warning: {
            DEFAULT: "var(--surface-warning-default)",
            hover: "var(--surface-warning-default-hover)",
            secondary: "var(--surface-warning-secondary)",
            "secondary-hover": "var(--surface-warning-secondary-hover)",
          },
          positive: {
            DEFAULT: "var(--surface-positive-default)",
            hover: "var(--surface-positive-default-hover)",
            secondary: "var(--surface-positive-secondary)",
            "secondary-hover": "var(--surface-positive-secondary-hover)",
          },
          disabled: {
            DEFAULT: "var(--surface-disabled-default)",
            hover: "var(--surface-disabled-default-hover)",
            secondary: "var(--surface-disabled-secondary)",
            "secondary-hover": "var(--surface-disabled-secondary-hover)",
          },
          scrim: "var(--surface-utilities-scrim)",
          overlay: "var(--surface-utilities-overlay)",
          hover: "var(--surface-utilities-hover)",
          "hover-inverse": "var(--surface-utilities-hover-inverse)",
          sticky: "var(--surface-utilities-sticky)",
        },
        // Semantic Text
        "text-token": {
          neutral: {
            DEFAULT: "var(--text-neutral-default)",
            secondary: "var(--text-neutral-secondary)",
            tertiary: "var(--text-neutral-tertiary)",
          },
          brand: {
            DEFAULT: "var(--text-brand-default)",
            "on-brand": "var(--text-brand-on-brand-default)",
          },
          "accent-1": {
            DEFAULT: "var(--text-accent-1-default)",
            "on-accent": "var(--text-accent-1-on-accent-1-default)",
            "on-accent-secondary": "var(--text-accent-1-on-accent-1-secondary)",
            "on-accent-tertiary": "var(--text-accent-1-on-accent-1-tertiary)",
          },
          "accent-2": {
            DEFAULT: "var(--text-accent-2-default)",
            "on-accent": "var(--text-accent-2-on-accent-2-default)",
          },
          danger: {
            DEFAULT: "var(--text-danger-default)",
            "on-danger-secondary": "var(--text-danger-on-danger-secondary)",
          },
          warning: {
            DEFAULT: "var(--text-warning-default)",
            "on-warning-secondary": "var(--text-warning-on-warning-secondary)",
          },
          positive: {
            DEFAULT: "var(--text-positive-default)",
            "on-positive-secondary": "var(--text-positive-on-positive-secondary)",
          },
          disabled: {
            DEFAULT: "var(--text-disabled-default)",
            "on-disabled": "var(--text-disabled-on-disabled-default)",
            "on-disabled-secondary": "var(--text-disabled-on-disabled-secondary)",
          },
          inverse: {
            DEFAULT: "var(--text-inverse-default)",
            secondary: "var(--text-inverse-secondary)",
            tertiary: "var(--text-inverse-tertiary)",
          },
        },
      },
      fontFamily: {
        heading: ["Rubik", "sans-serif"],
        body: ["Montserrat", "sans-serif"],
        rubik: ["Rubik", "sans-serif"],
        montserrat: ["Montserrat", "sans-serif"],
      },
      fontSize: {
        'display-giant': ['90px', { lineHeight: '98px', fontWeight: '600' }],
        'display-hero': ['68px', { lineHeight: '80px', fontWeight: '600' }],
        'h1': ['48px', { lineHeight: '60px', fontWeight: '600' }],
        'h2': ['38px', { lineHeight: '48px', fontWeight: '600' }],
        'h3': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'h4': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'title-base': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'title-base-regular': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'title-sm': ['12px', { lineHeight: '18px', fontWeight: '600' }],
        'title-sm-regular': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'title-xs-bold': ['10px', { lineHeight: '16px', fontWeight: '700' }],
        'title-xs-regular': ['10px', { lineHeight: '16px', fontWeight: '400' }],
        'body-p1': ['20px', { lineHeight: '28px', fontWeight: '400' }],
        'body-p2': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-p3': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'body-p4': ['10px', { lineHeight: '16px', fontWeight: '400' }],
      },
      borderRadius: {
        'card-sm': '24px',
        'card': '36px',
        'card-lg': '48px',
        'pill-lg': '64px',
        '4xl': '36px',
        '5xl': '48px',
        '6xl': '64px',
      },
      spacing: {
        '050': '2px',
        '150': '6px',
        '1200': '48px',
        '1600': '64px',
        '2400': '96px',
        '4000': '160px',
      },
      maxWidth: {
        'page': '1440px',
        'content': '1440px',
        'narrow': '600px',
        'cta': '500px',
      },
    },
  },
  plugins: [],
}
